export const MOCK_ORG = {
  orgName: 'Acme Corporation (Demo)',
  orgType: 'Enterprise Edition',
  isSandbox: false,
  instanceUrl: 'https://acme.my.salesforce.com',
  orgId: '00D000000000001',
  instanceName: 'NA100',
};

export const MOCK_OWD_DATA = {
  entities: [
    { QualifiedApiName: 'Account',     Label: 'Account',     InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Contact',     Label: 'Contact',     InternalSharingModel: 'ControlledByParent', ExternalSharingModel: 'ControlledByParent' },
    { QualifiedApiName: 'Opportunity', Label: 'Opportunity', InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Case',        Label: 'Case',        InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Read' },
    { QualifiedApiName: 'Lead',        Label: 'Lead',        InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Campaign',    Label: 'Campaign',    InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Contract',    Label: 'Contract',    InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Order',       Label: 'Order',       InternalSharingModel: 'ControlledByParent', ExternalSharingModel: 'ControlledByParent' },
    { QualifiedApiName: 'Invoice__c',  Label: 'Invoice',     InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Project__c',  Label: 'Project',     InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'ReadWrite' },
    { QualifiedApiName: 'Asset',       Label: 'Asset',       InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Read' },
    { QualifiedApiName: 'Quote',       Label: 'Quote',       InternalSharingModel: 'ControlledByParent', ExternalSharingModel: 'Private' },
  ],
};

export const MOCK_ROLE_DATA = {
  allRoles: [
    { Id: 'r1',  Name: 'CEO',                          ParentRoleId: null },
    { Id: 'r2',  Name: 'VP Sales',                     ParentRoleId: 'r1' },
    { Id: 'r3',  Name: 'VP Service',                   ParentRoleId: 'r1' },
    { Id: 'r4',  Name: 'VP Marketing',                 ParentRoleId: 'r1' },
    { Id: 'r5',  Name: 'Director Sales NA',            ParentRoleId: 'r2' },
    { Id: 'r6',  Name: 'Director Sales EMEA',          ParentRoleId: 'r2' },
    { Id: 'r7',  Name: 'Director Sales APAC',          ParentRoleId: 'r2' },
    { Id: 'r8',  Name: 'Director Service',             ParentRoleId: 'r3' },
    { Id: 'r9',  Name: 'Sales Manager East',           ParentRoleId: 'r5' },
    { Id: 'r10', Name: 'Sales Manager West',           ParentRoleId: 'r5' },
    { Id: 'r11', Name: 'Sales Manager Central',        ParentRoleId: 'r5' },
    { Id: 'r12', Name: 'Sales Manager UK',             ParentRoleId: 'r6' },
    { Id: 'r13', Name: 'Sales Manager DE',             ParentRoleId: 'r6' },
    { Id: 'r14', Name: 'Service Manager Tier1',        ParentRoleId: 'r8' },
    { Id: 'r15', Name: 'Service Manager Tier2',        ParentRoleId: 'r8' },
    { Id: 'r16', Name: 'Account Executive East',       ParentRoleId: 'r9' },
    { Id: 'r17', Name: 'Account Executive West',       ParentRoleId: 'r10' },
    { Id: 'r18', Name: 'SDR East',                     ParentRoleId: 'r9' },
    { Id: 'r19', Name: 'SDR West',                     ParentRoleId: 'r10' },
    { Id: 'r20', Name: 'Service Rep Tier1',            ParentRoleId: 'r14' },
    { Id: 'r21', Name: 'Service Rep Tier2',            ParentRoleId: 'r15' },
    { Id: 'r22', Name: 'DEPRECATED - Inside Sales',   ParentRoleId: 'r5' },
    { Id: 'r23', Name: 'DEPRECATED - Field Sales',    ParentRoleId: 'r6' },
    { Id: 'r24', Name: 'Contractor Role',              ParentRoleId: 'r1' },
  ],
  totalRoleCount: 24,
  topLevelRoleUsers: [
    { UserRoleId: 'r1', userCount: 3 },
  ],
  emptyRoles: [
    { Id: 'r22', Name: 'DEPRECATED - Inside Sales' },
    { Id: 'r23', Name: 'DEPRECATED - Field Sales'  },
    { Id: 'r24', Name: 'Contractor Role'           },
  ],
};

export const MOCK_TERRITORY_DATA = {
  enabled: true,
  models: [
    { Id: 'tm1', Name: 'Acme Sales Territories 2024', State: 'Active',   Description: 'Primary sales territory model' },
    { Id: 'tm2', Name: 'Acme Sales Territories 2023', State: 'Archived', Description: 'Prior year model' },
    { Id: 'tm3', Name: 'New Territory Model - Draft',  State: 'Planning', Description: '' },
  ],
  territories: [
    { Id: 't1',  Name: 'North America',      ParentTerritory2Id: null,  Territory2ModelId: 'tm1' },
    { Id: 't2',  Name: 'EMEA',               ParentTerritory2Id: null,  Territory2ModelId: 'tm1' },
    { Id: 't3',  Name: 'APAC',               ParentTerritory2Id: null,  Territory2ModelId: 'tm1' },
    { Id: 't4',  Name: 'East US',            ParentTerritory2Id: 't1',  Territory2ModelId: 'tm1' },
    { Id: 't5',  Name: 'West US',            ParentTerritory2Id: 't1',  Territory2ModelId: 'tm1' },
    { Id: 't6',  Name: 'Central US',         ParentTerritory2Id: 't1',  Territory2ModelId: 'tm1' },
    { Id: 't7',  Name: 'Canada',             ParentTerritory2Id: 't1',  Territory2ModelId: 'tm1' },
    { Id: 't8',  Name: 'UK & Ireland',       ParentTerritory2Id: 't2',  Territory2ModelId: 'tm1' },
    { Id: 't9',  Name: 'DACH',               ParentTerritory2Id: 't2',  Territory2ModelId: 'tm1' },
    { Id: 't10', Name: 'France & Benelux',   ParentTerritory2Id: 't2',  Territory2ModelId: 'tm1' },
    { Id: 't11', Name: 'ANZ',                ParentTerritory2Id: 't3',  Territory2ModelId: 'tm1' },
    { Id: 't12', Name: 'Japan',              ParentTerritory2Id: 't3',  Territory2ModelId: 'tm1' },
    { Id: 't13', Name: 'Southeast Asia',     ParentTerritory2Id: 't3',  Territory2ModelId: 'tm1' },
    { Id: 't14', Name: 'New York Metro',     ParentTerritory2Id: 't4',  Territory2ModelId: 'tm1' },
    { Id: 't15', Name: 'Mid-Atlantic',       ParentTerritory2Id: 't4',  Territory2ModelId: 'tm1' },
    { Id: 't16', Name: 'New England',        ParentTerritory2Id: 't4',  Territory2ModelId: 'tm1' },
    { Id: 't17', Name: 'California',         ParentTerritory2Id: 't5',  Territory2ModelId: 'tm1' },
    { Id: 't18', Name: 'Pacific Northwest',  ParentTerritory2Id: 't5',  Territory2ModelId: 'tm1' },
    { Id: 't19', Name: 'Southwest',          ParentTerritory2Id: 't5',  Territory2ModelId: 'tm1' },
    { Id: 't20', Name: 'Midwest',            ParentTerritory2Id: 't6',  Territory2ModelId: 'tm1' },
    { Id: 't21', Name: 'Texas',              ParentTerritory2Id: 't6',  Territory2ModelId: 'tm1' },
    // Empty territories (no users assigned)
    { Id: 't22', Name: 'DEPRECATED - Latin America', ParentTerritory2Id: 't1', Territory2ModelId: 'tm1' },
    { Id: 't23', Name: 'DEPRECATED - Middle East',   ParentTerritory2Id: 't2', Territory2ModelId: 'tm1' },
    { Id: 't24', Name: 'India - Placeholder',         ParentTerritory2Id: 't3', Territory2ModelId: 'tm1' },
  ],
  rules: [
    { Id: 'tr1', Territory2Id: 't4',  IsActive: true,  BooleanFilter: null },
    { Id: 'tr2', Territory2Id: 't5',  IsActive: true,  BooleanFilter: null },
    { Id: 'tr3', Territory2Id: 't8',  IsActive: false, BooleanFilter: null },
    { Id: 'tr4', Territory2Id: 't9',  IsActive: false, BooleanFilter: null },
    { Id: 'tr5', Territory2Id: 't11', IsActive: true,  BooleanFilter: null },
  ],
  userAssociations: [
    { Territory2Id: 't4',  userCount: 4 },
    { Territory2Id: 't5',  userCount: 3 },
    { Territory2Id: 't6',  userCount: 2 },
    { Territory2Id: 't7',  userCount: 2 },
    { Territory2Id: 't8',  userCount: 3 },
    { Territory2Id: 't9',  userCount: 2 },
    { Territory2Id: 't10', userCount: 2 },
    { Territory2Id: 't11', userCount: 2 },
    { Territory2Id: 't12', userCount: 1 },
    { Territory2Id: 't13', userCount: 2 },
    { Territory2Id: 't14', userCount: 3 },
    { Territory2Id: 't15', userCount: 2 },
    { Territory2Id: 't16', userCount: 1 },
    { Territory2Id: 't17', userCount: 4 },
    { Territory2Id: 't18', userCount: 2 },
    { Territory2Id: 't19', userCount: 2 },
    { Territory2Id: 't20', userCount: 3 },
    { Territory2Id: 't21', userCount: 3 },
    // t22, t23, t24 have no entries = 0 users
  ],
};

export const MOCK_SHARING_RULES_DATA = {
  ownerRules: [
    { Id: 'or0',  DeveloperName: 'Account_Owner_All_Internal',  'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'AllInternalUsers' },
    { Id: 'or1',  DeveloperName: 'Account_Owner_Sales_All',     'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'AllInternalUsers' },
    { Id: 'or2',  DeveloperName: 'Account_Owner_Corp_All',      'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'AllInternalUsers' },
    { Id: 'or3',  DeveloperName: 'Account_Owner_Exec_Vis',      'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'or4',  DeveloperName: 'Account_Owner_Dir_Vis',       'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'or5',  DeveloperName: 'Account_Owner_Mgr_Vis',       'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'or6',  DeveloperName: 'Account_Owner_EMEA',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'or7',  DeveloperName: 'Account_Owner_APAC',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'or8',  DeveloperName: 'Opp_Owner_Sales_Dir',         'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or9',  DeveloperName: 'Opp_Owner_VP_Vis',            'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or10', DeveloperName: 'Opp_Owner_Exec_Vis',          'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or11', DeveloperName: 'Opp_Owner_Sales_Mgr',         'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or12', DeveloperName: 'Opp_Owner_Sales_Ops',         'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or13', DeveloperName: 'Opp_Owner_Forecast',          'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'or14', DeveloperName: 'Case_Owner_Support',          'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'or15', DeveloperName: 'Case_Owner_Mgr_Vis',          'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'or16', DeveloperName: 'Case_Owner_Escalation',       'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'or17', DeveloperName: 'Lead_Owner_Sales_Vis',        'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
  ],
  criteriaRules: [
    { Id: 'cr0',  DeveloperName: 'Account_Criteria_Enterprise',    'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr1',  DeveloperName: 'Account_Criteria_Strategic',     'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr2',  DeveloperName: 'Account_Criteria_Named',         'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr3',  DeveloperName: 'Account_Criteria_Region_NA',     'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr4',  DeveloperName: 'Account_Criteria_Region_EMEA',   'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr5',  DeveloperName: 'Account_Criteria_Region_APAC',   'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr6',  DeveloperName: 'Account_Criteria_Partner',       'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Group' },
    { Id: 'cr7',  DeveloperName: 'Account_Criteria_Renewal',       'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr8',  DeveloperName: 'Account_Criteria_CS_Vis',        'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr9',  DeveloperName: 'Account_Criteria_Marketing',     'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr10', DeveloperName: 'Account_Criteria_Finance',       'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr11', DeveloperName: 'Account_Criteria_Legal',         'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr12', DeveloperName: 'Account_Criteria_Old1',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr13', DeveloperName: 'Account_Criteria_Old2',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr14', DeveloperName: 'Account_Criteria_Old3',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr15', DeveloperName: 'Account_Criteria_Old4',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr16', DeveloperName: 'Account_Criteria_Old5',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr17', DeveloperName: 'Account_Criteria_Old6',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr18', DeveloperName: 'Account_Criteria_Old7',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr19', DeveloperName: 'Account_Criteria_Old8',          'EntityDefinition.QualifiedApiName': 'Account',     'SharedTo.Type': 'Role' },
    { Id: 'cr20', DeveloperName: 'Opp_Criteria_Amount_High',       'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr21', DeveloperName: 'Opp_Criteria_Stage_Close',       'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr22', DeveloperName: 'Opp_Criteria_Enterprise',        'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr23', DeveloperName: 'Opp_Criteria_Renewal',           'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr24', DeveloperName: 'Opp_Criteria_Partner',           'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Group' },
    { Id: 'cr25', DeveloperName: 'Opp_Criteria_CS',                'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr26', DeveloperName: 'Opp_Criteria_Finance',           'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr27', DeveloperName: 'Opp_Criteria_Legal',             'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr28', DeveloperName: 'Opp_Criteria_Old1',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr29', DeveloperName: 'Opp_Criteria_Old2',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr30', DeveloperName: 'Opp_Criteria_Old3',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr31', DeveloperName: 'Opp_Criteria_Old4',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr32', DeveloperName: 'Opp_Criteria_Old5',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr33', DeveloperName: 'Opp_Criteria_Old6',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr34', DeveloperName: 'Opp_Criteria_Old7',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr35', DeveloperName: 'Opp_Criteria_Old8',              'EntityDefinition.QualifiedApiName': 'Opportunity', 'SharedTo.Type': 'Role' },
    { Id: 'cr36', DeveloperName: 'Case_Criteria_Priority_High',    'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr37', DeveloperName: 'Case_Criteria_Escalated',        'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr38', DeveloperName: 'Case_Criteria_VIP_Account',      'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr39', DeveloperName: 'Case_Criteria_Product_A',        'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr40', DeveloperName: 'Case_Criteria_Product_B',        'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr41', DeveloperName: 'Case_Criteria_Finance',          'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr42', DeveloperName: 'Case_Criteria_Legal',            'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr43', DeveloperName: 'Case_Criteria_Partner',          'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Group' },
    { Id: 'cr44', DeveloperName: 'Case_Criteria_Old1',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr45', DeveloperName: 'Case_Criteria_Old2',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr46', DeveloperName: 'Case_Criteria_Old3',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr47', DeveloperName: 'Case_Criteria_Old4',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr48', DeveloperName: 'Case_Criteria_Old5',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr49', DeveloperName: 'Case_Criteria_Old6',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr50', DeveloperName: 'Case_Criteria_Old7',             'EntityDefinition.QualifiedApiName': 'Case',        'SharedTo.Type': 'Role' },
    { Id: 'cr51', DeveloperName: 'Lead_Criteria_Enterprise',       'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr52', DeveloperName: 'Lead_Criteria_Region_NA',        'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr53', DeveloperName: 'Lead_Criteria_Region_EMEA',      'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr54', DeveloperName: 'Lead_Criteria_Partner',          'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Group' },
    { Id: 'cr55', DeveloperName: 'Lead_Criteria_Marketing',        'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr56', DeveloperName: 'Lead_Criteria_SDR',              'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr57', DeveloperName: 'Lead_Criteria_Old1',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr58', DeveloperName: 'Lead_Criteria_Old2',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr59', DeveloperName: 'Lead_Criteria_Old3',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr60', DeveloperName: 'Lead_Criteria_Old4',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr61', DeveloperName: 'Lead_Criteria_Old5',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr62', DeveloperName: 'Lead_Criteria_Old6',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr63', DeveloperName: 'Lead_Criteria_Old7',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr64', DeveloperName: 'Lead_Criteria_Old8',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr65', DeveloperName: 'Lead_Criteria_Old9',             'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
    { Id: 'cr66', DeveloperName: 'Lead_Criteria_Old10',            'EntityDefinition.QualifiedApiName': 'Lead',        'SharedTo.Type': 'Role' },
  ],
};

export const MOCK_MANUAL_SHARING_DATA = {
  manualShares: [
    { object: 'Account',     count: 3847  },
    { object: 'Case',        count: 12304 },
    { object: 'Opportunity', count: 891   },
    { object: 'Contact',     count: 234   },
    { object: 'Lead',        count: 56    },
    { object: 'Campaign',    count: 12    },
  ],
};

export const MOCK_APEX_SHARING_DATA = {
  withoutSharingClasses: [
    { name: 'AccountSharingService',      id: 'a1'  },
    { name: 'CaseEscalationHandler',      id: 'a2'  },
    { name: 'OpportunityCloneUtility',    id: 'a3'  },
    { name: 'LeadConversionController',   id: 'a4'  },
    { name: 'IntegrationCallbackHandler', id: 'a5'  },
    { name: 'DataMigrationBatch',         id: 'a6'  },
    { name: 'ReportingDataService',       id: 'a7'  },
    { name: 'TerritoryAssignmentJob',     id: 'a8'  },
    { name: 'QuoteGeneratorController',   id: 'a9'  },
    { name: 'PartnerPortalService',       id: 'a10' },
    { name: 'LegacyDataLoader',           id: 'a11' },
    { name: 'InvoiceProcessingBatch',     id: 'a12' },
  ],
  sharesCreatingClasses: [
    { name: 'AccountSharingService',   id: 'a1'  },
    { name: 'OpportunityTeamSyncJob',  id: 'a13' },
    { name: 'PartnerPortalService',    id: 'a10' },
  ],
  customSharingReasons: [
    { DeveloperName: 'Partner_Access',    Label: 'Partner Access',    'ParentObject.DeveloperName': 'Account'     },
    { DeveloperName: 'Executive_Review',  Label: 'Executive Review',  'ParentObject.DeveloperName': 'Opportunity' },
    { DeveloperName: 'Service_Escalation',Label: 'Service Escalation','ParentObject.DeveloperName': 'Case'        },
  ],
};

export const MOCK_RECORD_TEAMS_DATA = {
  accountTeam: {
    enabled: true,
    members: [
      ...Array.from({ length: 145 }, (_, i) => ({
        AccountId: `acc${i}`,
        TeamMemberRole: i % 3 === 0 ? 'Account Manager' : 'Sales Support',
        AccountAccessLevel: i % 4 === 0 ? 'Edit' : 'Read',
      })),
    ],
  },
  caseTeam: {
    enabled: true,
    templates: [
      { Id: 'ct1', Name: 'Standard Support Team'   },
      { Id: 'ct2', Name: 'Escalation Team'          },
      { Id: 'ct3', Name: 'Executive Response Team'  },
    ],
  },
  oppTeam: {
    enabled: true,
    members: [
      ...Array.from({ length: 89 }, (_, i) => ({
        OpportunityId: `opp${i}`,
        TeamMemberRole: i % 2 === 0 ? 'Account Executive' : 'Sales Engineer',
        OpportunityAccessLevel: i % 3 === 0 ? 'Edit' : 'Read',
      })),
    ],
  },
};

export const MOCK_GROUPS_QUEUES_DATA = {
  groups: [
    { Id: 'g1',  Name: 'All Internal Users',            Type: 'Regular', DeveloperName: 'AllInternalUsers'    },
    { Id: 'g2',  Name: 'Sales Team',                    Type: 'Regular', DeveloperName: 'Sales_Team'           },
    { Id: 'g3',  Name: 'Service Team',                  Type: 'Regular', DeveloperName: 'Service_Team'         },
    { Id: 'g4',  Name: 'Executive Group',               Type: 'Regular', DeveloperName: 'Executive_Group'      },
    { Id: 'g5',  Name: 'DEPRECATED - Old Sales Group',  Type: 'Regular', DeveloperName: 'Old_Sales_Group'      },
    { Id: 'g6',  Name: 'DEPRECATED - Legacy Tier',      Type: 'Regular', DeveloperName: 'Legacy_Tier'          },
    { Id: 'g7',  Name: 'Partner Users',                 Type: 'Regular', DeveloperName: 'Partner_Users'        },
    { Id: 'g8',  Name: 'Case Queue - Tier 1',           Type: 'Queue',   DeveloperName: 'Case_Queue_T1'        },
    { Id: 'g9',  Name: 'Case Queue - Tier 2',           Type: 'Queue',   DeveloperName: 'Case_Queue_T2'        },
    { Id: 'g10', Name: 'Lead Queue - Enterprise',       Type: 'Queue',   DeveloperName: 'Lead_Queue_Enterprise'},
    { Id: 'g11', Name: 'Lead Queue - SMB',              Type: 'Queue',   DeveloperName: 'Lead_Queue_SMB'       },
    { Id: 'g12', Name: 'DEPRECATED - Old Case Queue',  Type: 'Queue',   DeveloperName: 'Old_Case_Queue'       },
  ],
  groupMemberCounts: [
    { GroupId: 'g1',  memberCount: 247 },
    { GroupId: 'g2',  memberCount: 89  },
    { GroupId: 'g3',  memberCount: 45  },
    { GroupId: 'g4',  memberCount: 6   },
    { GroupId: 'g5',  memberCount: 0   },
    { GroupId: 'g6',  memberCount: 0   },
    { GroupId: 'g7',  memberCount: 23  },
    { GroupId: 'g8',  memberCount: 12  },
    { GroupId: 'g9',  memberCount: 8   },
    { GroupId: 'g10', memberCount: 5   },
    { GroupId: 'g11', memberCount: 3   },
    { GroupId: 'g12', memberCount: 0   },
  ],
  queues: [
    { Id: 'g8',  Name: 'Case Queue - Tier 1'          },
    { Id: 'g9',  Name: 'Case Queue - Tier 2'          },
    { Id: 'g10', Name: 'Lead Queue - Enterprise'      },
    { Id: 'g11', Name: 'Lead Queue - SMB'             },
    { Id: 'g12', Name: 'DEPRECATED - Old Case Queue' },
  ],
  queueObjects: [
    { QueueId: 'g8',  SobjectType: 'Case' },
    { QueueId: 'g9',  SobjectType: 'Case' },
    { QueueId: 'g10', SobjectType: 'Lead' },
    { QueueId: 'g11', SobjectType: 'Lead' },
    { QueueId: 'g12', SobjectType: 'Case' },
  ],
};

export const MOCK_PERMISSION_BYPASSES_DATA = {
  viewAllDataUsers: [
    { Id: 'u1', Name: 'Sarah Mitchell',       Profile: { Name: 'System Administrator'  } },
    { Id: 'u2', Name: 'James Thornton',       Profile: { Name: 'System Administrator'  } },
    { Id: 'u3', Name: 'Integration User',     Profile: { Name: 'System Administrator'  } },
    { Id: 'u4', Name: 'David Chen',           Profile: { Name: 'Sales Director Profile' } },
    { Id: 'u5', Name: 'ReportingService API', Profile: { Name: 'API User'              } },
    { Id: 'u6', Name: 'DataWarehouse Sync',   Profile: { Name: 'API User'              } },
    { Id: 'u7', Name: 'Marcus Williams',      Profile: { Name: 'Sales Director Profile' } },
    { Id: 'u8', Name: 'Patricia Nguyen',      Profile: { Name: 'Marketing Manager'     } },
  ],
  modifyAllDataUsers: [
    { Id: 'u1', Name: 'Sarah Mitchell',     Profile: { Name: 'System Administrator' } },
    { Id: 'u2', Name: 'James Thornton',     Profile: { Name: 'System Administrator' } },
    { Id: 'u3', Name: 'Integration User',   Profile: { Name: 'System Administrator' } },
    { Id: 'u6', Name: 'DataWarehouse Sync', Profile: { Name: 'API User'             } },
  ],
  viewAllObjectPerms: [
    { Id: 'vp0',  SobjectType: 'Account',         PermissionsViewAllRecords: true },
    { Id: 'vp1',  SobjectType: 'Contact',          PermissionsViewAllRecords: true },
    { Id: 'vp2',  SobjectType: 'Opportunity',      PermissionsViewAllRecords: true },
    { Id: 'vp3',  SobjectType: 'Case',             PermissionsViewAllRecords: true },
    { Id: 'vp4',  SobjectType: 'Lead',             PermissionsViewAllRecords: true },
    { Id: 'vp5',  SobjectType: 'Campaign',         PermissionsViewAllRecords: true },
    { Id: 'vp6',  SobjectType: 'Contract',         PermissionsViewAllRecords: true },
    { Id: 'vp7',  SobjectType: 'Order',            PermissionsViewAllRecords: true },
    { Id: 'vp8',  SobjectType: 'Invoice__c',       PermissionsViewAllRecords: true },
    { Id: 'vp9',  SobjectType: 'Quote',            PermissionsViewAllRecords: true },
    { Id: 'vp10', SobjectType: 'Asset',            PermissionsViewAllRecords: true },
    { Id: 'vp11', SobjectType: 'Project__c',       PermissionsViewAllRecords: true },
    { Id: 'vp12', SobjectType: 'KnowledgeArticle', PermissionsViewAllRecords: true },
    { Id: 'vp13', SobjectType: 'Task',             PermissionsViewAllRecords: true },
  ],
  modifyAllObjectPerms: [
    { Id: 'mp0', SobjectType: 'Account',     PermissionsModifyAllRecords: true },
    { Id: 'mp1', SobjectType: 'Contact',     PermissionsModifyAllRecords: true },
    { Id: 'mp2', SobjectType: 'Opportunity', PermissionsModifyAllRecords: true },
    { Id: 'mp3', SobjectType: 'Case',        PermissionsModifyAllRecords: true },
    { Id: 'mp4', SobjectType: 'Lead',        PermissionsModifyAllRecords: true },
    { Id: 'mp5', SobjectType: 'Campaign',    PermissionsModifyAllRecords: true },
    { Id: 'mp6', SobjectType: 'Contract',    PermissionsModifyAllRecords: true },
  ],
};

export const MOCK_IMPLICIT_SHARING_DATA = {
  entities: [
    { QualifiedApiName: 'Account',     Label: 'Account',     InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Contact',     Label: 'Contact',     InternalSharingModel: 'ControlledByParent', ExternalSharingModel: 'ControlledByParent' },
    { QualifiedApiName: 'Case',        Label: 'Case',        InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Read' },
    { QualifiedApiName: 'Opportunity', Label: 'Opportunity', InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
    { QualifiedApiName: 'Asset',       Label: 'Asset',       InternalSharingModel: 'ReadWrite',         ExternalSharingModel: 'Read' },
    { QualifiedApiName: 'Contract',    Label: 'Contract',    InternalSharingModel: 'Private',           ExternalSharingModel: 'Private' },
  ],
};

export const MOCK_EXTERNAL_ACCESS_DATA = {
  guestProfiles: [
    { Id: 'gp1', Name: 'Partner Community Guest'  },
    { Id: 'gp2', Name: 'Customer Community Guest' },
  ],
  externalEntities: [
    { QualifiedApiName: 'Case',       Label: 'Case',    ExternalSharingModel: 'Read'      },
    { QualifiedApiName: 'Asset',      Label: 'Asset',   ExternalSharingModel: 'Read'      },
    { QualifiedApiName: 'Project__c', Label: 'Project', ExternalSharingModel: 'ReadWrite' },
    { QualifiedApiName: 'Invoice__c', Label: 'Invoice', ExternalSharingModel: 'Read'      },
  ],
};
